#!/bin/zsh

PKG="fypm"

# Fypm
alias tan="$PKG ta-annotate"
alias tastart="$PKG ta-start"
alias tastop="$PKG ta-stop"
alias tin="$PKG ti-annotate"
alias ticart="$PKG ti-start-correction"
alias ticend="$PKG ti-end-correction"
alias tistart="$PKG ti-start"
alias tiend="$PKG ti-end"
alias tir="$PKG ti-track"

# TaskWarrior
alias twui="taskwarrior-tui"
alias talc="task const"
alias tals="_tals blist"
alias talss="_tals alarms"
alias ttals="task TYPE.not:SubTask -Ghost list"
alias taconls="task TYPE:Continuous description.hasnt:Versionamento -Divisory list"
alias taconlss="task TYPE:Continuous description.hasnt:Versionamento -Divisory all"
alias tagoals="_tadatels GOAL goals"
alias tagoalss="_tadatels GOAL all-goals"
alias taduels="_tadatels due list"
alias taduelss="_tadatels due all"
alias taals="_tadatels ALARM list"
alias taalss="_tadatels ALARM all"
alias taschls="_tadatels scheduled list"
alias taschlss="_tadatels scheduled all"

# TimeWarrior
alias tiils='timew summary :ids'

