#!/bin/zsh

CURRENT_WT=Example1
CURRENT_LGT=off

# --------------- WorkTime --------------- #
if [[ $(date +%H%M) -lt 0830 ]]; then
    echo "export DISPLAY=$DISPLAY && $TWBIN/worktime Example1" | at 08:30
else
    CURRENT_WT=Example1
fi
if [[ $(date +%H%M) -lt 1000 ]]; then
    echo "export DISPLAY=$DISPLAY && $TWBIN/worktime Example2" | at 10:00
else
    CURRENT_WT=Example3
fi
if [[ $(date +%H%M) -lt 1400 ]]; then
    echo "export DISPLAY=$DISPLAY && $TWBIN/worktime Example3" | at 14:00
else
    CURRENT_WT=Example3
fi
if [[ $(date +%H%M) -lt 1800 ]]; then
    echo "export DISPLAY=$DISPLAY && $TWBIN/worktime Example4" | at 18:00
else
    CURRENT_WT=Example4
fi
if [[ $(date +%H%M) -lt 1900 ]]; then
    echo "export DISPLAY=$DISPLAY && $TWBIN/worktime Sleep" | at 19:00
else
    CURRENT_WT=Sleep
fi

$TWBIN/worktime $CURRENT_WT

# --------------- Lighting --------------- #
if [[ $(date +%H%M) -lt 1700 ]]; then
    echo "export DISPLAY=$DISPLAY && $MYBIN/lighting night" | at 17:00
else
    CURRENT_LGT=night
fi
if [[ $(date +%H%M) -lt 1800 ]]; then
    echo "export DISPLAY=$DISPLAY && $MYBIN/lighting presleep" | at 18:30
else
    CURRENT_LGT=presleep
fi

$MYBIN/lighting $CURRENT_LGT


# ---------------- Others ---------------- #
#echo "/bin/killall DiscordPTB" | at 18:00
#echo "pkill -SIGTERM X" | at 19:30

#yes | andrun -2 "echo 'wol $HOSTMAC' | at 06:00"
